#ifndef CEGUI_GLFW3_HPP
#define CEGUI_GLFW3_HPP 1



#include "CEGUI/CEGUI.h"
#include "CEGUI/WindowManager.h"


#include "sgfxapi/sgfxapi.glcommon.hpp"

#include <map>


static int translate_glfw3_cegui(int key){
   static const std::map<int, int> CEGUI_GLFW3_KEYMAPPINGS = {
      {GLFW_KEY_UNKNOWN       , CEGUI::Key::Unknown}, 
      {GLFW_KEY_SPACE         , CEGUI::Key::Space},
      {GLFW_KEY_APOSTROPHE    , CEGUI::Key::Apostrophe},
      {GLFW_KEY_COMMA         , CEGUI::Key::Comma},
      {GLFW_KEY_MINUS         , CEGUI::Key::Minus},
      {GLFW_KEY_PERIOD        , CEGUI::Key::Period},
      {GLFW_KEY_SLASH         , CEGUI::Key::Slash},
      {GLFW_KEY_0             , CEGUI::Key::Zero},
      {GLFW_KEY_1             , CEGUI::Key::One},
      {GLFW_KEY_2             , CEGUI::Key::Two},
      {GLFW_KEY_3             , CEGUI::Key::Three},
      {GLFW_KEY_4             , CEGUI::Key::Four},
      {GLFW_KEY_5             , CEGUI::Key::Five},
      {GLFW_KEY_6             , CEGUI::Key::Six},
      {GLFW_KEY_7             , CEGUI::Key::Seven},
      {GLFW_KEY_8             , CEGUI::Key::Eight},
      {GLFW_KEY_9             , CEGUI::Key::Nine},
      {GLFW_KEY_SEMICOLON     , CEGUI::Key::Semicolon},
      {GLFW_KEY_EQUAL         , CEGUI::Key::Equals},
      {GLFW_KEY_A             , CEGUI::Key::A},
      {GLFW_KEY_B             , CEGUI::Key::B},
      {GLFW_KEY_C             , CEGUI::Key::C},
      {GLFW_KEY_D             , CEGUI::Key::D},
      {GLFW_KEY_E             , CEGUI::Key::E},
      {GLFW_KEY_F             , CEGUI::Key::F},
      {GLFW_KEY_G             , CEGUI::Key::G},
      {GLFW_KEY_H             , CEGUI::Key::H},
      {GLFW_KEY_I             , CEGUI::Key::I},
      {GLFW_KEY_J             , CEGUI::Key::J},
      {GLFW_KEY_K             , CEGUI::Key::K},
      {GLFW_KEY_L             , CEGUI::Key::L},
      {GLFW_KEY_M             , CEGUI::Key::M},
      {GLFW_KEY_N             , CEGUI::Key::N},
      {GLFW_KEY_O             , CEGUI::Key::O},
      {GLFW_KEY_P             , CEGUI::Key::P},
      {GLFW_KEY_Q             , CEGUI::Key::Q},
      {GLFW_KEY_R             , CEGUI::Key::R},
      {GLFW_KEY_S             , CEGUI::Key::S},
      {GLFW_KEY_T             , CEGUI::Key::T},
      {GLFW_KEY_U             , CEGUI::Key::U},
      {GLFW_KEY_V             , CEGUI::Key::V},
      {GLFW_KEY_W             , CEGUI::Key::W},
      {GLFW_KEY_X             , CEGUI::Key::X},
      {GLFW_KEY_Y             , CEGUI::Key::Y},
      {GLFW_KEY_Z             , CEGUI::Key::Z},
      {GLFW_KEY_LEFT_BRACKET  , CEGUI::Key::LeftBracket},
      {GLFW_KEY_BACKSLASH     , CEGUI::Key::Backslash},
      {GLFW_KEY_RIGHT_BRACKET , CEGUI::Key::RightBracket},
      {GLFW_KEY_GRAVE_ACCENT  , CEGUI::Key::Grave},
      {GLFW_KEY_WORLD_1       , CEGUI::Key::Unknown},
      {GLFW_KEY_WORLD_2       , CEGUI::Key::Unknown},
      {GLFW_KEY_ESCAPE        , CEGUI::Key::Escape},
      {GLFW_KEY_ENTER         , CEGUI::Key::Return},
      {GLFW_KEY_TAB           , CEGUI::Key::Tab},
      {GLFW_KEY_BACKSPACE     , CEGUI::Key::Backspace},
      {GLFW_KEY_INSERT        , CEGUI::Key::Insert},
      {GLFW_KEY_DELETE        , CEGUI::Key::Delete},
      {GLFW_KEY_RIGHT         , CEGUI::Key::ArrowRight},
      {GLFW_KEY_LEFT          , CEGUI::Key::ArrowLeft},
      {GLFW_KEY_DOWN          , CEGUI::Key::ArrowDown},
      {GLFW_KEY_UP            , CEGUI::Key::ArrowUp},
      {GLFW_KEY_PAGE_UP       , CEGUI::Key::PageUp},
      {GLFW_KEY_PAGE_DOWN     , CEGUI::Key::PageDown},
      {GLFW_KEY_HOME          , CEGUI::Key::Home},
      {GLFW_KEY_END           , CEGUI::Key::End},
      {GLFW_KEY_CAPS_LOCK     , CEGUI::Key::Capital},
      {GLFW_KEY_SCROLL_LOCK   , CEGUI::Key::ScrollLock},
      {GLFW_KEY_NUM_LOCK      , CEGUI::Key::NumLock},
      {GLFW_KEY_PRINT_SCREEN  , CEGUI::Key::SysRq},
      {GLFW_KEY_PAUSE         , CEGUI::Key::Pause},
      {GLFW_KEY_F1            , CEGUI::Key::F1},
      {GLFW_KEY_F2            , CEGUI::Key::F2},
      {GLFW_KEY_F3            , CEGUI::Key::F3},
      {GLFW_KEY_F4            , CEGUI::Key::F4},
      {GLFW_KEY_F5            , CEGUI::Key::F5},
      {GLFW_KEY_F6            , CEGUI::Key::F6},
      {GLFW_KEY_F7            , CEGUI::Key::F7},
      {GLFW_KEY_F8            , CEGUI::Key::F8},
      {GLFW_KEY_F9            , CEGUI::Key::F9},
      {GLFW_KEY_F10           , CEGUI::Key::F10},
      {GLFW_KEY_F11           , CEGUI::Key::F11},
      {GLFW_KEY_F12           , CEGUI::Key::F12},
      {GLFW_KEY_F13           , CEGUI::Key::F13},
      {GLFW_KEY_F14           , CEGUI::Key::F14},
      {GLFW_KEY_F15           , CEGUI::Key::F15},
      {GLFW_KEY_F16           , CEGUI::Key::Unknown},
      {GLFW_KEY_F17           , CEGUI::Key::Unknown},
      {GLFW_KEY_F18           , CEGUI::Key::Unknown},
      {GLFW_KEY_F19           , CEGUI::Key::Unknown},
      {GLFW_KEY_F20           , CEGUI::Key::Unknown},
      {GLFW_KEY_F21           , CEGUI::Key::Unknown},
      {GLFW_KEY_F22           , CEGUI::Key::Unknown},
      {GLFW_KEY_F23           , CEGUI::Key::Unknown},
      {GLFW_KEY_F24           , CEGUI::Key::Unknown},
      {GLFW_KEY_F25           , CEGUI::Key::Unknown},
      {GLFW_KEY_KP_0          , CEGUI::Key::Numpad0},
      {GLFW_KEY_KP_1          , CEGUI::Key::Numpad1},
      {GLFW_KEY_KP_2          , CEGUI::Key::Numpad2},
      {GLFW_KEY_KP_3          , CEGUI::Key::Numpad3},
      {GLFW_KEY_KP_4          , CEGUI::Key::Numpad4},
      {GLFW_KEY_KP_5          , CEGUI::Key::Numpad5},
      {GLFW_KEY_KP_6          , CEGUI::Key::Numpad6},
      {GLFW_KEY_KP_7          , CEGUI::Key::Numpad7},
      {GLFW_KEY_KP_8          , CEGUI::Key::Numpad8},
      {GLFW_KEY_KP_9          , CEGUI::Key::Numpad9},
      {GLFW_KEY_KP_DECIMAL    , CEGUI::Key::Decimal},
      {GLFW_KEY_KP_DIVIDE     , CEGUI::Key::Divide},
      {GLFW_KEY_KP_MULTIPLY   , CEGUI::Key::Multiply},
      {GLFW_KEY_KP_SUBTRACT   , CEGUI::Key::Subtract},
      {GLFW_KEY_KP_ADD        , CEGUI::Key::Add},
      {GLFW_KEY_KP_ENTER      , CEGUI::Key::NumpadEnter},
      {GLFW_KEY_KP_EQUAL      , CEGUI::Key::NumpadEquals},     
      {GLFW_KEY_LEFT_SHIFT    , CEGUI::Key::LeftShift},
      {GLFW_KEY_LEFT_CONTROL  , CEGUI::Key::LeftControl},
      {GLFW_KEY_LEFT_ALT      , CEGUI::Key::LeftAlt},
      {GLFW_KEY_LEFT_SUPER    , CEGUI::Key::LeftWindows},
      {GLFW_KEY_RIGHT_SHIFT   , CEGUI::Key::RightShift},
      {GLFW_KEY_RIGHT_CONTROL , CEGUI::Key::RightControl},
      {GLFW_KEY_RIGHT_ALT     , CEGUI::Key::RightAlt},
      {GLFW_KEY_RIGHT_SUPER   , CEGUI::Key::RightWindows},
      {GLFW_KEY_MENU          , CEGUI::Key::AppMenu},
      {GLFW_KEY_LAST          , CEGUI::Key::AppMenu}
   };

   auto it = CEGUI_GLFW3_KEYMAPPINGS.find(key);

   if (it == CEGUI_GLFW3_KEYMAPPINGS.end())
      return CEGUI::Key::Unknown;

   return (*it).second;
}

#endif
